### ISSUE TITLE
An idea for more user-friendly human-readable output (at the cost of verbosity).

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/gostatus#29]
This is an idea for how to make the default human-readable output of `gostatus` more friendly towards people seeing/using the tool that are not extremely familiar with it (like I am). Thanks to @audreylim for the suggestion!

### Current Output

The current output puts each repository on a single line, prepended with 4 possible cryptic symbols like:

```
  +  github.com/dchest/uniuri/...
  +  github.com/syndtr/goleveldb/...
b    github.com/shurcooL/go-goon/...
 *-  github.com/shurcooL/Conception-go/...
  #  github.com/russross/blackfriday/...
   $ github.com/microcosm-cc/bluemonday/...
```

Unless you've created this tool (like I did), or use it nearly daily (like I often do), the above output will probably make no sense unless you spend the time to look at the legend (which you'll hopefully find in `gostatus -help` or in README, instead of quitting in frustration):

```
Legend:
  ???? - Not under (recognized) version control
  b - Non-master branch checked out
  * - Uncommited changes in working dir
  + - Update available
  - - Local revision is ahead of remote (need to push?)
  ! - No remote
  # - Remote path doesn't match import path
  $ - Stash exists
```

## Proposed Output

Instead, I could make the default output more friendly towards use without having to memorize cryptic symbols. It's inspired by how I produce output in another tool [`binstale`](https://github.com/shurcooL/binstale#readme).

The general idea is to print the repo import path first, and then underneath it write short bullet points for each interesting property of the repo (if there's nothing interesting, the entire repository is omitted from output, unless `-v` flag is used). Something like this:

```
github.com/dchest/uniuri/...
	update is available: commit 12345abc (you have 11111def)
github.com/syndtr/goleveldb/...
	update is available: commit 67890bce (you have 22222fed)
github.com/shurcooL/go-goon/...
	non-default branch is checked out: dev (default is master)
github.com/shurcooL/Conception-go/...
	dirty working tree, including files: main.go highligt.go
	local revision ahead of remote: commit 23456be (remote has 112233ced)
github.com/russross/blackfriday/...
	remote doesn't match import path: https://github.com/shurcooL/blackfriday
github.com/microcosm-cc/bluemonday/...
	stash(es) exist: 2 stashes
```

This is also inspired by the output of `git status`. It uses easy to understand language to explain the status of a git repository, rather than cryptic symbols.

If there's a huge demand, I can preserve the current dense output mode under an optional flag, but I think this new presentation mode will be an overall improvement to users of `gostatus`.

I welcome initial feedback. I'll also implement this on a branch and try it myself first, and see how I like it.

**Comment by shurcooL** [comment]
After thinking more about how I use `gostatus` myself, I think I would still want to preserve the more compact but hard to read current mode behind a flag.

Given that, it might be helpful to include the same symbols in the more verbose version, to help teach users and make it a more seamless transition between verbose and short modes.

**Comment by shurcooL** [comment]
Some feedback on the output above:

> I really like the output example you gave in https://github.com/shurcooL/gostatus/issues/29#issuecomment-177715254
> that makes a lot of sense to me and the special characters make it nice too

I think I'll implement that, and make it the default. That should make the tool easier to use for new people. For people who know the special characters by memory and prefer more dense output (i.e., the current output), there will be a flag.

**Comment by joeblew99** [comment]
I also was wondering about this.
the way you proposed on the Feb 1 comment looks pretty good.

Also it might be good to support a JSON format, so that I and others can use it to build workflows on top of go status ?  Maybe IDE's, but i am more thinking to help build basic tools for a team.
Also we all know that dependencies can be controlled with glide, godep etc etc. So many now i am loosing count. But it woudl be great to be able to use this with those tools ?

**Comment by shurcooL** [comment]
When implementing this change, I will add a new flag to have the current compact inline output:

```
  -c	Compact output with inline notation.
```

I'm also considering renaming the current `-v` flag to `-all`, to avoid it being confusing:

```
  -all
    	Show all Go packages, not just ones with notable status.
```

**Comment by shurcooL** [comment]
This is done now.

`gostatus all` should produce much more human readable output. Thanks again to @audreylim for the idea!

To produce the same compact output as before, use `-c` flag. E.g., `gostatus -c all`.

(The `-v` flag to display all packages, even if they have no outstanding status, remains unchanged.)

**Comment by shurcooL** [comment]
I got an idea on a further iteration of this.

Currently, the compact output is like this:

```bash
  +$ github.com/gopherjs/gopherjs/...
 *+  github.com/gregjones/httpcache/...
  !  github.com/shurcooL/asanaissues/...
```

And normal output is like this:

```bash
github.com/gopherjs/gopherjs/...
	+ Update available
	$ Stash exists
github.com/gregjones/httpcache/...
	* Uncommited changes in working dir
	+ Update available
github.com/shurcooL/asanaissues/...
	! No remote
```

I found that the more verbose output is obviously easier to read and understand, especially when not familiar with the symbols. But it's harder to scan and see what's up at a glance.

However, it might make sense to actually make normal output more like compact:

```
  +$ github.com/gopherjs/gopherjs/...
	+ Update available
	$ Stash exists
 *+  github.com/gregjones/httpcache/...
	* Uncommited changes in working dir
	+ Update available
  !  github.com/shurcooL/asanaissues/...
	! No remote
```

That way it's best of both worlds IMO. It's still easy to scan over many many packages. It's easy to look up what each symbol means.

Also, this way, the normal mode prepares you better for compact mode when you use `gostatus` very often.

**Comment by joeblew99** [comment]
My 2 cents.

Make is automation friendly. JSON would be the obvious way.
Architecturally, you can then convert the JSON to a human readable form. Then you only support one format internally - the JSON format.

As far as the uman readable format, i personally liked the example approach of:

````
github.com/gopherjs/gopherjs/...
        + Update available
        $ Stash exists
github.com/gregjones/httpcache/...
        * Uncommited changes in working dir
        + Update available
github.com/shurcooL/asanaissues/...
        ! No remote
````

But a easy to parse machine readable format it really need at least for me, because then other flows can be done on top:
- i can inform a big team
- i can inform the CI system
- i can swap out dependencies at the CI level, and do smoke tests
- some others....

**Comment by shurcooL** [comment]
Automation friendly output should be another issue, and it's a feature request. The current -debug mode happens to be JSON, but it outputs lower level information than the tool normally outputs.

I'm going to implement the change I considered in https://github.com/shurcooL/gostatus/issues/29#issuecomment-219237760 and see what happens. Feedback welcome.

**Comment by joeblew99** [comment]
Ok good stuff.
