### ISSUE TITLE
Lots of "Remote path doesn't match import path"

### ISSUE THREAD

**Issue by eduncan911** [shurcooL/gostatus#32]
So, the vast majority of my repos have the `#` or *"Remote path doesn't match import path"* message.

    $ cd ~/go/src
    $ gostatus -c all
      ....
      #  github.com/spf13/afero/...
      #  github.com/spf13/cast/...
      #  github.com/spf13/fsync/...
      #  github.com/spf13/cobra/...
      #  github.com/spf13/hugo/...
      ....

But, they do match....

    $ cd $GOPATH/src/github.com/spf13/hugo
    $ git remote -v
    origin  git@github.com:spf13/hugo (fetch)
    origin  git@github.com:spf13/hugo (push)

So what is this message actually saying?

**Comment by shurcooL** [comment]
This looks like a duplicate of #30, but it adds validation to that it might be helpful to compare import paths in a protocol-agnostic way.

> So what is this message actually saying?

Currently, it checks if the two match verbatim, and displays `#` status if not:

```Go
if !*fFlag && (r.Local.RemoteURL != r.Remote.RepoURL) {
	s += "\n	# Remote path doesn't match import path"
}
```

**Comment by eduncan911** [comment]
Yep, that's exactly the issue.  Protocol comparisons.

FYI, I enforce `ssh` for all of my `git` needs:

```
$ cat .gitconfig
(...snip...)
[url "git@github.com:"]
        insteadOf = https://github.com/
```

So even if the `go get` tool tries to use https://github.com, I force it to git@ instead.

You, closing this ticket as it is a duplicate of #30 .
