### ISSUE TITLE
Provide more detailed error message for mismatched import paths

### ISSUE THREAD

**Issue by kjk** [shurcooL/gostatus#33]
Using the latest version of gostatus:
```
Krzysztofs-MacBook-Pro:quicknotes kjk$ gostatus .
github.com/kjk/quicknotes/...
	# Remote path doesn't match import path
```

It would be good if error message printed both paths.

As an additional bonus, it would be good to document most common cases for such error somewhere (a wiki, a gist, a blog post) and also print a link to this document as part of error message. As it stands, I have no clue why this is happening, how to debug it further or whether it's a bug, an omission or a design decision.

The underlying reason might be same as issue #30 or maybe it's because it's as private repo that I `git clone-d` as opposed to `go get-ted`.

**Comment by kjk** [comment]
Too lazy to do proper PR, this is what I had in mind: https://github.com/kjk/gostatus/commit/6a28a2f47261dfc1eb5ec19cd019f81dd261fb5b

**Comment by shurcooL** [comment]
> It would be good if error message printed both paths.
>
> Too lazy to do proper PR, this is what I had in mind: https://github.com/kjk/gostatus/commit/6a28a2f47261dfc1eb5ec19cd019f81dd261fb5b

This is a good idea, I'll take it. Thanks. It's trivial implement so no need for PR.

> As an additional bonus, it would be good to document most common cases for such error somewhere (a wiki, a gist, a blog post) and also print a link to this document as part of error message.

That's also a good thing to do.

> As it stands, I have no clue why this is happening, how to debug it further or whether it's a bug, an omission or a design decision.

Until this is implemented, you can do `gostatus -debug .`, but that's clearly a mode meant for developers/debugging, not for normal usage.

**Comment by kjk** [comment]
My case was https:// != git@ mismatch caused by doing `git clone`. I assume this is the most common case, so my comment about more docs is moot unless there are some other common cases for such mismatch that can't be easily fixed.
