### ISSUE TITLE
Remote URL mismatch message can be misleading due to different URL protocols.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/gostatus#39]
Originally reported by @mafredri in https://github.com/shurcooL/gostatus/issues/37#issuecomment-225291305:

> the error message should be made less confusing. Instead of:
> 
> ```
> # Remote URL (git@github.com:mafredri/go-gaussian.git) doesn't match repo URL inferred from import path (https://github.com/mafredri/go-gaussian)
> ```
> 
> It would say:
> 
> ```
> # Remote URL (git@github.com:mafredri/go-gaussian.git) doesn't match repo URL inferred from import path (git@github.com:mafredri/go-gaussian)
> ```
> 
> By matching the protocol used, the user would not be lead as much astray as to why the error is popping up.

**Comment by mvdan** [comment]
I would even argue that it shouldn't throw this warning if the only difference is the protocol. It throws it for every single package of mine in `github.com/mvdan/...`, which is not very useful.

I understand that this is tricky, but perhaps it should be supported for `github.com` as a start since it's a rather simple change that will cover most of these.

**Comment by shurcooL** [comment]
> I would even argue that it shouldn't throw this warning if the only difference is the protocol. It throws it for every single package of mine in `github.com/mvdan/...`, which is not very useful.

Can you elaborate? Ever since #30 has been resolved, the protocol is ignored and remote urls are considered equal if the only difference is in protocol.

Are you by any chance referring to the `.git` suffix in the path being different? If so, that's intended, read https://github.com/shurcooL/gostatus/issues/30#issuecomment-217706664.

This issue is about making the message more clear when there is a difference in the path.

**Comment by mvdan** [comment]
> Can you elaborate? Ever since #30 has been resolved, the protocol is ignored and remote urls are considered equal if the only difference is in protocol.

Whoops, my bad for not doing research. I was assuming this was the issue and forgot about the `.git`.

> Are you by any chance referring to the .git suffix in the path being different? If so, that's intended, read #30 (comment).

I assume you're treating `.git` as part of the path, and thus treating it as a different (mismatching) import path?

I understand your reasoning, but I would still argue that this is a false positive in the error. I don't know if Github works without the `.git` with the ssh URLs, but I'm sure there are other services like it out there that would break without it (I think GitLab does).

It should be pretty straightforward to teach the tool that `.git` at the end of an ssh URL is to be ignored. If that's too problematic in the general case, it could be applied only to a set of hosts, such as `github.com` and `gitlab.com`.

**Comment by shurcooL** [comment]
Fixed in cf96920.

Before:

	# Remote URL (git@github.com:shurcooL/wrongrepo) doesn't match repo URL inferred from import path (https://github.com/shurcooL/gostatus)

After:

	# Remote URL doesn't match repo URL inferred from import path:
		  (actual) git@github.com:shurcooL/wrongrepo
		(expected) git@github.com:shurcooL/gostatus
